services:
  roon-server:
    hostname: RoonServer
    build: .
    # image: hey
    container_name: roon-server
    restart: always
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #  - /path/to/data:/data
    #ports:
    #  - 8000:8000
    #  - 9000:9000
    networks:
    - macvlan

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: enp5s0
    ipam:
      config:
        - subnet: "192.168.11.0/24"
          ip_range: "192.168.11.64/26"
          gateway: "192.168.11.1"
